Repository hoops-project/frontend, pull requests merged in 2024-05, with the labels that each got.

#4 hoops #3 공통 컴포넌트(버튼, 뱃지, 선택박스, 회원가입 인풋) 생성
  package-lock.json
  package.json
  src/App.style.ts
  src/App.tsx
  src/components/common/AuthInput/AuthInput.style.ts
  src/components/common/AuthInput/AuthInput.tsx
  src/components/common/Badge/Badge.style.ts
  src/components/common/Badge/Badge.tsx
  src/components/common/BasicButton/BasicButton.style.ts
  src/components/common/BasicButton/BasicButton.tsx
  src/components/common/SelectBox/SelectBox.style.ts
  src/components/common/SelectBox/SelectBox.tsx
  src/types/signIn.ts
Labels: enhancement

#8 hoops #5 메인 페이지 레이아웃 구성 및 필요 컴포넌트 생성
  package-lock.json
  package.json
  src/assets/banner.png
  src/assets/friends.svg
  src/assets/girl.svg
  src/assets/last-game.svg
  src/assets/make-group.svg
  src/assets/my-game.jpg
  src/components/Calender/Calender.style.ts
  src/components/Calender/Calender.tsx
  src/components/MainCarousel/MainCarousel.style.ts
  src/components/MainCarousel/MainCarousel.tsx
  src/components/MainNav/MainNav.style.ts
  src/components/MainNav/MainNav.tsx
  src/components/MainSelectList/MainSelectList.tsx
  src/components/MatchItem/MatchItem.style.ts
  src/components/MatchItem/MatchItem.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/common/BasicButton/BasicButton.style.ts
  src/components/common/BasicButton/BasicButton.tsx
  src/components/common/SelectBox/SelectBox.tsx
  src/components/common/Slider/Slider.style.ts
  src/components/common/Slider/Slider.tsx
  src/hooks/useMainSelect.ts
  src/layout/Header/Header.style.ts
  src/pages/Main/Main.style.ts
  src/pages/Main/Main.tsx
  src/styles/commonStyle.ts
  src/types/match.ts
  src/types/select.ts
  src/types/type.ts
Labels: enhancement

#11 hoops #9 로그인 페이지 생성
  src/assets/check-mark.webp
  src/assets/kakao.svg
  src/components/common/AuthInput/AuthInput.style.ts
  src/components/common/AuthInput/AuthInput.tsx
  src/components/common/BasicButton/BasicButton.style.ts
  src/components/common/BasicButton/BasicButton.tsx
  src/constants/validRules.ts
  src/layout/Header/Header.style.ts
  src/layout/Header/Header.tsx
  src/pages/Main/Main.style.ts
  src/pages/Main/Main.tsx
  src/pages/SignIn/SignIn.style.ts
  src/pages/SignIn/SignIn.tsx
  src/routes/MainRouter.tsx
  src/styles/GlobalStyle.ts
  src/styles/commonStyle.ts
  src/types/auth.ts
  src/types/button.ts
Labels: enhancement

#13 hoops #12 회원가입 페이지 생성
  src/components/common/AuthInput/AuthInput.style.ts
  src/components/common/AuthInput/AuthInput.tsx
  src/components/common/SelectButton/SelectButton.style.ts
  src/components/common/SelectButton/SelectButton.tsx
  src/constants/signUpSelect.ts
  src/constants/validRules.ts
  src/hooks/useDuplicate.ts
  src/layout/ChangeBgLayout/ChangeBgLayout.style.ts
  src/layout/ChangeBgLayout/ChangeBgLayout.tsx
  src/layout/DefaultLayout/DefaultLayout.tsx
  src/pages/SignIn/SignIn.style.ts
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/SignUp.style.ts
  src/pages/SignUp/SignUp.tsx
  src/routes/MainRouter.tsx
  src/styles/commonStyle.ts
  src/styles/theme.ts
  src/types/auth.ts
  src/types/button.ts
Labels: enhancement

#18 hoops #16 경기내용 상세 페이지 생성
  src/assets/Background.png
  src/assets/ic_info_gender.svg
  src/assets/ic_info_max_player_cnt.svg
  src/assets/ic_info_shoes.svg
  src/assets/ic_info_stadium.svg
  src/assets/ic_matchdata_lock.svg
  src/components/KakaoMap/KakaoMap.style.ts
  src/components/KakaoMap/KakaoMap.tsx
  src/components/LockMatchData/LockMatchData.style.ts
  src/components/LockMatchData/LockMatchData.tsx
  src/components/MatchItem/MatchItem.tsx
  src/hooks/UseSearchPlacesOptions.ts
  src/pages/Detail/Detail.style.ts
  src/pages/Detail/Detail.tsx
  src/pages/Main/Main.tsx
  src/routes/MainRouter.tsx
  src/styles/theme.ts
  src/types/detail.ts
  src/types/match.ts
Labels: enhancement

#20 hoops #19 프로젝트 라우팅 방식 리펙토링 및 page파일 컴포넌트 세분화
  src/App.tsx
  src/components/DetailTopTitle/DetailTopTitle.style.ts
  src/components/DetailTopTitle/DetailTopTitle.tsx
  src/components/JoinGame/JoinGame.style.ts
  src/components/JoinGame/JoinGame.tsx
  src/components/KakaoMap/KakaoMap.style.ts
  src/components/KakaoMap/KakaoMap.tsx
  src/components/LocationSearchForm/LocationSearchForm.style.ts
  src/components/LocationSearchForm/LocationSearchForm.tsx
  src/components/MainSelectList/MainSelectList.style.ts
  src/components/MatchPoint/MatchPoint.style.ts
  src/components/MatchPoint/MatchPoint.tsx
  src/components/SignInForm/SignInForm.style.ts
  src/components/SignInForm/SignInForm.tsx
  src/components/SignUpForm/SignUpForm.style.ts
  src/components/SignUpForm/SignUpForm.tsx
  src/constants/queryKeys.ts
  src/constants/regex.ts
  src/constants/selectOption.ts
  src/constants/signUpSelect.ts
  src/constants/validRules.ts
  src/layout/DefaultLayout/DefaultLayout.tsx
  src/layout/Header/Header.tsx
  src/pages/AddGame/AddGame.style.ts
  src/pages/AddGame/AddGame.tsx
  src/pages/Detail/Detail.style.ts
  src/pages/Detail/Detail.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/SignIn/SignIn.style.ts
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/SignUp.style.ts
  src/pages/SignUp/SignUp.tsx
  src/routes/MainRouter.tsx
  src/styles/commonStyle.ts
  src/styles/theme.ts
Labels: enhancement

#23 hoops #21 마이페이지 생성
  src/assets/Vector.svg
  src/assets/fluent-emoji-flat_bell.svg
  src/components/FriendRequestList/FriendRequestList.style.ts
  src/components/FriendRequestList/FriendRequestList.tsx
  src/components/GameInviteList/GameInviteList.tsx
  src/components/MainSelectList/MainSelectList.style.ts
  src/components/Notification/Notification.style.ts
  src/components/Notification/Notification.tsx
  src/components/SignInForm/SignInForm.style.ts
  src/components/SignInForm/SignInForm.tsx
  src/components/SignUpForm/SignUpForm.style.ts
  src/components/SignUpForm/SignUpForm.tsx
  src/components/UserInfoEdit/UserInfoEdit.style.ts
  src/components/UserInfoEdit/UserInfoEdit.tsx
  src/components/common/AuthInput/AuthInput.tsx
  src/components/common/BasicInput/BasicInput.style.ts
  src/components/common/SelectButton/SelectButton.style.ts
  src/components/common/SelectButton/SelectButton.tsx
  src/components/common/UserInfoSelect/UserInfoSelect.tsx
  src/helper/findSelectIndex.ts
  src/hooks/useSelect.ts
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/routes/MainRouter.tsx
  src/styles/commonStyle.ts
  src/styles/theme.ts
  src/types/button.ts
  src/types/input.ts
  src/types/select.ts
Labels: enhancement

#27 hoops #25 MSW를 설치 및 기본 셋팅
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/constants/endPoint.ts
  src/constants/validRules.ts
  src/helper/deepFreeze.ts
  src/main.tsx
  src/mock/db.json
  src/mock/handler/auth/handler.ts
  src/mock/handler/chat/handler.ts
  src/mock/handler/firends/handler.ts
  src/mock/handler/gameUser/handler.ts
  src/mock/handler/gmaeCreator/handler.ts
  src/mock/handler/manager/handler.ts
  src/mock/handler/report/handler.ts
  src/mock/handler/user/handler.ts
  src/mock/index.ts
  src/mock/setupWorker.ts
Labels: enhancement

#30 hoops #28 나의 경기 페이지 생성
  src/assets/enter_door.svg
  src/assets/invite.png
  src/assets/pin.svg
  src/assets/report_icon.svg
  src/assets/send.svg
  src/components/ChatList/ChatList.style.ts
  src/components/ChatList/ChatList.tsx
  src/components/FriendRequestList/FriendRequestList.style.ts
  src/components/FriendRequestList/FriendRequestList.tsx
  src/components/GameChat/GameChat.style.ts
  src/components/GameChat/GameChat.tsx
  src/components/GameInviteList/GameInviteList.tsx
  src/components/GameUserList/GameUserList.style.ts
  src/components/GameUserList/GameUserList.tsx
  src/components/MainNav/MainNav.tsx
  src/components/MyGameItem/MyGameItem.style.ts
  src/components/MyGameItem/MyGameItem.tsx
  src/components/MyGameList/MyGameList.style.ts
  src/components/MyGameList/MyGameList.tsx
  src/components/ParticipationGameList/ParticipationGameList.style.ts
  src/components/ParticipationGameList/ParticipationGameList.tsx
  src/components/WaitChatSelect/WaitChatSelect.style.ts
  src/components/WaitChatSelect/WaitChatSelect.tsx
  src/components/common/RequestItem/RequestItem.style.ts
  src/components/common/RequestItem/RequestItem.tsx
  src/hooks/temp.ts
  src/pages/MyGame/MyGame.style.ts
  src/pages/MyGame/MyGame.tsx
  src/routes/MainRouter.tsx
  src/types/game.ts
Labels: enhancement

#33 hoops #32 인피니티 스크롤을 편하게 구현하기 위한 커스텀 훅 생성
  src/hooks/useInfiniteScroll.ts
Labels: enhancement

#34 hoops #31 참가신청 후의 경기 상세 페이지 작성
  package-lock.json
  package.json
  src/components/MatchData/MatchData.style.ts
  src/components/MatchData/MatchData.tsx
  src/mock/data.ts
  src/pages/Detail/Detail.tsx
Labels: enhancement

#39 hoops #38 vercel 배포를 위한 GitHub Actions 설정 파일 추가
  .github/workflows/deploy.yml
  build.sh
Labels: enhancement

#42 hoops #37 친구 검색 페이지 작성 및 User정보 목데이터 연동
  src/components/SearchTab/SearchTab.style.ts
  src/components/SearchTab/SearchTab.tsx
  src/mock/data.ts
  src/routes/MainRouter.tsx
Labels: enhancement

#46 Hoops #44 나의 지난 경기 리스트 페이지
  src/components/common/MyLastGame/MyLastGame.style.ts
  src/components/common/MyLastGame/MyLastGame.tsx
  src/mock/data.ts
  src/pages/MyLastGame/MyLastGame.style.ts
  src/pages/MyLastGame/MyLastGame.tsx
  src/routes/MainRouter.tsx
Labels: enhancement

#48 hoops #47 react-icon을 이용한 일부 아이콘 통일화 작업
  package-lock.json
  package.json
  src/components/GameUserList/GameUserList.style.ts
  src/components/GameUserList/GameUserList.tsx
  src/components/MyGameItem/MyGameItem.style.ts
  src/components/MyGameItem/MyGameItem.tsx
  src/components/Notification/Notification.style.ts
  src/components/Notification/Notification.tsx
  src/components/common/RequestItem/RequestItem.style.ts
  src/components/common/RequestItem/RequestItem.tsx
Labels: enhancement

#52 hoops #51 오타로 인한 에러 수정
  src/components/common/RequestItem/RequestItem.tsx
Labels: bug

#55 hoops#54 오류 수정 및 라우팅 추가
  src/components/MainNav/MainNav.tsx
  src/components/MatchData/MatchData.tsx
Labels: bug

#59 hoops #58 vite.config.ts 의 proxy 설정을 통한 CORS 문제 해결 및 연동 테스트
  src/api/QueryClient.ts
  src/api/axiosInstance.ts
  src/components/Calender/Calender.tsx
  src/constants/queryKeys.ts
  src/hooks/query/useGameList.ts
  src/pages/Main/Main.tsx
  src/store/calender.ts
  vite.config.ts
Labels: enhancement

#61 hoops #60 Main페이지 서버 연동 및 인피티니 스크롤과 필터링 적용
  src/components/MatchItem/MatchItem.tsx
  src/components/common/SelectBox/SelectBox.tsx
  src/constants/selectOption.ts
  src/helper/convertValueToName.ts
  src/helper/dateGenerater.ts
  src/helper/generateObjectsArray.ts
  src/hooks/query/useGameList.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/Main/Main.style.ts
  src/pages/Main/Main.tsx
  src/styles/commonStyle.ts
  src/types/match.ts
Labels: enhancement

#65 hoops #63 회원가입 페이지 서버연동 및 중복검사 수행
  src/components/KakaoMap/SearchPlaceKakaoMap/SearchPlaceKakaoMap.tsx
  src/components/SignUpForm/SignUpForm.style.ts
  src/components/SignUpForm/SignUpForm.tsx
  src/components/common/BasicButton/BasicButton.style.ts
  src/components/common/BasicButton/BasicButton.tsx
  src/helper/convertValueToName.ts
  src/hooks/query/useGetGameListQuery.ts
  src/hooks/query/useSignUpQuery.ts
  src/hooks/useSearchPlacesOptions.ts
  src/pages/Main/Main.tsx
  src/types/auth.ts
Labels: enhancement

#67 [fix] 로그인 시 header에 Access-Token 값이 담기지 않는 문제 해결
  src/api/axiosInstance.ts
  src/constants/endPoint.ts
  src/hooks/query/useLoginQuery.ts
  src/types/auth.ts
Labels: bug, enhancement

#68 hoops #66 경기 생성 페이지 서버 연동 및 쿼리 작성
  src/components/GameSelectList/GameSelectList.tsx
  src/components/common/BasicTextArea/BasicTextArea.style.ts
  src/components/common/BasicTextArea/BasicTextArea.tsx
  src/constants/regex.ts
  src/constants/selectOption.ts
  src/constants/validRules.ts
  src/helper/generateObjectsArray.ts
  src/hooks/query/useAddGameQuery.ts
  src/hooks/useGameInfo.ts
  src/pages/AddGame/AddGame.style.ts
  src/pages/AddGame/AddGame.tsx
  src/types/game.ts
Labels: enhancement

#71 hoops #69 마이페이지 프로필 수정 기능 완성
  src/components/UserInfoEdit/UserInfoEdit.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/helper/convertValueToName.ts
  src/helper/findSelectIndex.ts
  src/hooks/query/useUserInfoQuery.ts
  src/hooks/useSelect.ts
Labels: enhancement

#73 hoops #70 프라이빗 라우팅 및 로그아웃/회원탈퇴 기능 구현
  src/api/axiosInstance.ts
  src/components/Notification/Notification.style.ts
  src/components/Notification/Notification.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useDeactivateQuery.ts
  src/hooks/query/useLoginQuery.ts
  src/layout/DefaultLayout/DefaultLayout.tsx
  src/pages/SignIn/SignIn.tsx
  src/routes/MainRouter.tsx
  src/routes/PrivateRoute.tsx
Labels: bug, enhancement

#75 hoops #72 경기 내용 상세 페이지 서버 연동
  src/components/JoinGame/JoinGame.style.ts
  src/components/JoinGame/JoinGame.tsx
  src/components/KakaoMap/KakaoMap.tsx
  src/components/MatchData/MatchData.tsx
  src/components/MatchPoint/MatchPoint.tsx
  src/components/Notification/Notification.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/helper/generateObjectsArray.ts
  src/hooks/query/useAddGameQuery.ts
  src/hooks/query/useGameDetailQuery.ts
  src/hooks/query/useUserInfoQuery.ts
  src/pages/Detail/Detail.tsx
  src/types/detail.ts
Labels: enhancement

#81 hoops #79 유저 아이디 찾기 페이지 생성 및 서버 연동
  src/components/FindUserIdForm/FindUserId.style.ts
  src/components/FindUserIdForm/FindUserId.tsx
  src/hooks/query/useFindUserIdQuery.ts
  src/pages/FindUserId/FindUserId.style.ts
  src/pages/FindUserId/FindUserId.tsx
  src/pages/SignIn/SignIn.tsx
  src/routes/MainRouter.tsx
Labels: enhancement

#83 hoops #82 비밀번호 찾기 페이지 생성 및 서버 연동 완료
  src/components/FIndUserPasswordFrom/FindUserPasswordForm.tsx
  src/components/FindUserIdForm/FindUserId.tsx
  src/hooks/query/useFindAccount.ts
  src/hooks/query/useFindUserIdQuery.ts
  src/pages/FIndUserPassword/FIndUserPassword.tsx
  src/routes/MainRouter.tsx
Labels: enhancement

#85 hoops #80 나의 지난 경기 리스트 페이지 구현 및 서버 연동
  src/components/common/MyLastGame/MyLastGame.style.ts
  src/components/common/MyLastGame/MyLastGame.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useGetMyLastGameListQuery.ts
  src/types/game.ts
Labels: enhancement

#88 hoops #87 현재까지 취합된 오류를 수정
  src/api/axiosInstance.ts
  src/components/GameChat/GameChat.tsx
  src/components/MainNav/MainNav.style.ts
  src/components/MainNav/MainNav.tsx
  src/components/Notification/Notification.tsx
  src/components/SearchTab/SearchTab.style.ts
  src/components/SearchTab/SearchTab.tsx
  src/components/common/FriendModalList/FriendModalList.style.ts
  src/components/common/FriendModalList/FriendModalList.tsx
  src/components/common/Modal/Modal.style.ts
  src/components/common/ModalTit/ModalTit.style.ts
  src/components/common/MyFriend/MyFriend.style.ts
  src/components/common/MyFriend/MyFriend.tsx
  src/hooks/query/useLoginQuery.ts
  src/types/auth.ts
Labels: bug, enhancement

#89 hoops #84 메인 페이지 검색 기능 구현
  src/components/SearchInput/SearchInput.style.ts
  src/components/SearchInput/SearchInput.tsx
  src/constants/queryKeys.ts
  src/hooks/query/useEditGameQuery.ts
  src/hooks/query/useSearchGameQuery.ts
  src/hooks/useDebounce.ts
Labels: enhancement

#92 [fix] 추가적으로 발견된 오류 해결
  src/api/axiosInstance.ts
  src/hooks/query/useGetMyLastGameListQuery.ts
Labels: bug

#94 hoops #86 친구 탭 부분 서버 연동 및 검색 기능 구현
  src/api/axiosInstance.ts
  src/components/FriendList/FriendList.tsx
  src/components/MainNav/MainNav.tsx
  src/components/SearchResult/SearchResult.style.ts
  src/components/SearchResult/SearchResult.tsx
  src/components/SearchTab/SearchTab.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useGetFriendListQuery.ts
  src/hooks/query/useSearchFriendsQuery.ts
  src/types/auth.ts
  tsconfig.json
Labels: bug, enhancement

#96 hoops #93 웹소켓 연결 로직 작성 및 경기 참여 유저 & 유저 신고 기능 완성
  package-lock.json
  package.json
  src/components/ChatList/ChatList.tsx
  src/components/FriendList/FriendList.tsx
  src/components/GameChat/GameChat.tsx
  src/components/GameUserList/GameUserList.style.ts
  src/components/GameUserList/GameUserList.tsx
  src/components/MyGameItem/MyGameItem.tsx
  src/components/MyGameList/MyGameList.style.ts
  src/components/MyGameList/MyGameList.tsx
  src/components/common/BasicTextArea/BasicTextArea.style.ts
  src/components/common/BasicTextArea/BasicTextArea.tsx
  src/components/common/ModalSubText/ModalSubText.style.ts
  src/components/common/ModalSubText/ModalSubText.tsx
  src/constants/endPoint.ts
  src/hooks/query/useAddGameQuery.ts
  src/hooks/query/useGetChatListQuery.ts
  src/hooks/query/useReportQuery.ts
  src/hooks/useWebSocket.ts
  src/types/game.ts
  vite.config.ts
Labels: enhancement

#98 hoops #97 초대 가능한 친구 리스트 및 초대 요청, 위치 정보 표시
  src/components/FriendList/FriendList.tsx
  src/components/GameChat/GameChat.tsx
  src/components/InviteFriendList/InviteFriendList.tsx
  src/components/KakaoMap/KakaoMap.tsx
  src/components/MainNav/MainNav.tsx
  src/components/MyGameItem/MyGameItem.tsx
  src/components/MyGameList/MyGameList.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useGetGameListQuery.ts
  src/hooks/query/useInviteFriendQuery.ts
  src/types/auth.ts
Labels: enhancement

#100 hoops #95 경기 참가 신청 기능 완성
  src/api/axiosInstance.ts
  src/components/JoinGame/JoinGame.tsx
  src/components/KakaoMap/KakaoMap.tsx
  src/components/common/Modal/Modal.style.ts
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useJoinGameQuery.ts
  src/pages/SignIn/SignIn.tsx
Labels: bug, enhancement

#102 hoops #101 매너점수 평가 기능 완성
  src/api/axiosInstance.ts
  src/components/MannerRating/MannerRating.style.ts
  src/components/MannerRating/MannerRating.tsx
  src/components/common/MyLastGame/MyLastGame.tsx
  src/components/common/Review/Review.style.ts
  src/components/common/Review/Review.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useGetMannerRatingQuery.ts
  src/hooks/query/usePostRating.tsx
  src/pages/SignIn/SignIn.tsx
Labels: enhancement

#103 hoops #99 채팅 기능 및 알림 기능 구현
  package-lock.json
  package.json
  src/components/ChatList/ChatList.tsx
  src/components/FriendRequestList/FriendRequestList.style.ts
  src/components/FriendRequestList/FriendRequestList.tsx
  src/components/GameChat/GameChat.tsx
  src/components/GameInviteList/GameInviteList.tsx
  src/components/MyGameList/MyGameList.tsx
  src/components/Notification/Notification.tsx
  src/components/ParticipationGameList/ParticipationGameList.style.ts
  src/components/ParticipationGameList/ParticipationGameList.tsx
  src/components/common/Modal/Modal.style.ts
  src/components/common/MyPageUserInfo/MyPageUserInfo.tsx
  src/components/common/RequestItem/RequestItem.tsx
  src/constants/endPoint.ts
  src/constants/queryKeys.ts
  src/hooks/query/useExitGame.ts
  src/hooks/query/useFriendRequestQuery.ts
  src/hooks/query/useGameDetailQuery.ts
  src/hooks/query/useGameInviteQuery.ts
  src/hooks/query/useGetChatListQuery.ts
  src/hooks/query/useLoginQuery.ts
  src/hooks/query/useNotificationQuery.ts
  src/hooks/query/useParticipantGameQuery.ts
  src/hooks/useWebSocket.ts
  src/layout/DefaultLayout/DefaultLayout.tsx
  src/main.tsx
  src/store/store.ts
  src/types/friendRequest.ts
  src/types/invite.ts
  src/types/notification.ts
  vite.config.ts
Labels: enhancement

#106 [feat] main 브랜치 정기 병합 오류 수정 후 재병합
  src/hooks/query/useJoinGameQuery.ts
Labels: bug

#107 hotfix: 엑시오스 인스턴스 경로 수정
  src/api/axiosInstance.ts
Labels: bug

#108 hotfix: 배포문제 수정
  package-lock.json
  src/api/axiosInstance.ts
Labels: bug

#109 hotfix: 채팅은 /api 이 빠져서 요청해야 하기에 연결이 안되는 문제 해결
  src/api/axiosInstance.ts
  src/constants/endPoint.ts
  src/hooks/useWebSocket.ts
Labels: bug

#110 hotfix: vercel.json 설정 파일 추가
  .vercel.json
  src/components/GameChat/GameChat.tsx
  src/hooks/query/useExitGame.ts
  src/pages/SignIn/SignIn.tsx
Labels: bug

#111 hotfix: baseURL 변경
  .vercel.json
  src/api/axiosInstance.ts
Labels: bug

#112 hotfix: 알림 구독시 주소를 잘못 입력하여 404 에러가 발생한 문제 해결
  src/constants/endPoint.ts
  src/layout/DefaultLayout/DefaultLayout.tsx
Labels: bug

#113 fix: 알림 구독 URL이 배포된 서버 URL 로 바뀌지 않고 있었던 문제 수정
  src/layout/DefaultLayout/DefaultLayout.tsx
Labels: bug

#114 fix: 알림 구독 url "/api" 누락 수정
  src/layout/DefaultLayout/DefaultLayout.tsx
Labels: bug

#121 fix: 로그인 오류 해결
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/OAuthRedirect/OAuthRedirect.tsx
  src/routes/MainRouter.tsx
Labels: bug

#122 fix: 소셜로그인 리다이렉트 관련 오류 해결
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/OAuthRedirect/OAuthRedirect.tsx
  src/routes/MainRouter.tsx
Labels: bug

#123 fix: 소셜 로그인시 헤더 아이콘 변경이 안되는 문제 해결 및 메인 페이지 날짜 문제 수정
  src/components/Calender/Calender.tsx
  src/components/OAuthRedirect/OAuthRedirect.tsx
Labels: bug

#127 hoops#115 친구 신청 및 삭제 기능 구현
  src/components/GameUserList/GameUserList.tsx
  src/components/SearchResult/SearchResult.tsx
  src/hooks/query/useFriendActions.ts
Labels: enhancement

#128 feat: 최종 병합
  src/components/GameUserList/GameUserList.style.ts
  src/components/GameUserList/GameUserList.tsx
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/MyGameList/MyGameList.style.ts
  src/components/MyGameList/MyGameList.tsx
  src/components/Notification/Notification.tsx
  src/components/OAuthRedirect/OAuthRedirect.tsx
  src/components/ParticipationGameList/ParticipationGameList.style.ts
  src/components/ParticipationGameList/ParticipationGameList.tsx
  src/components/SearchResult/SearchResult.tsx
  src/components/SignInForm/SignInForm.tsx
  src/hooks/query/useFriendActions.ts
Labels: enhancement

#130 hoops #129 채팅 기능중 이전 채팅 내용 불러오기 기능 추가
  src/components/ChatList/ChatList.tsx
  src/hooks/useWebSocket.ts
Labels: enhancement

#132 [fix] 기능 추가 후 최종 병합
  src/components/ChatList/ChatList.tsx
  src/components/SearchResult/SearchResult.tsx
  src/hooks/useWebSocket.ts
Labels: bug, enhancement

#133 fix: 카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 수정
  src/layout/Header/Header.tsx
Labels: bug

#134 fix: 카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 다시 수정
  src/components/OAuthRedirect/OAuthRedirect.tsx
  src/layout/Header/Header.tsx
Labels: bug

#135 hotfix: 경기 참여 및 경기 참여 요청 수락시 데이터가 업데이트가 안되는 문제 수정
  src/components/Notification/Notification.tsx
  src/components/SearchInput/SearchInput.style.ts
  src/components/SearchInput/SearchInput.tsx
  src/hooks/query/useAcceptGameRequestQuery.ts
  src/hooks/query/useGetFriendListQuery.ts
  src/hooks/query/useParticipantGameQuery.ts
  src/hooks/useWebSocket.ts
  src/pages/Report/Report.tsx
Labels: bug, enhancement

#136 fix: 지난경기 불러올때 한번에 불러오는 size 수 변경
  src/hooks/query/useGetMyLastGameListQuery.ts
Labels: bug

#137 hotfix: 신고하기 엔드포인트 오류 수정
  src/components/FriendList/FriendList.tsx
  src/components/GameUserList/GameUserList.tsx
  src/components/ReportItem/ReportItem.tsx
  src/components/common/MyFriend/MyFriend.tsx
  src/constants/endPoint.ts
  src/hooks/query/useReportQuery.ts
  src/main.tsx
  src/types/auth.ts
Labels: bug
